# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'accel_sensor.ui'
#
# Created: Wed Oct 12 19:06:54 2011
#      by: PyQt4 UI code generator 4.7.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_AccelSensorMainWindow(object):
    def setupUi(self, AccelSensorMainWindow):
        AccelSensorMainWindow.setObjectName("AccelSensorMainWindow")
        AccelSensorMainWindow.resize(748, 771)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(AccelSensorMainWindow.sizePolicy().hasHeightForWidth())
        AccelSensorMainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtGui.QWidget(AccelSensorMainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame = QtGui.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.frame)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.mpl = MplWidget(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mpl.sizePolicy().hasHeightForWidth())
        self.mpl.setSizePolicy(sizePolicy)
        self.mpl.setObjectName("mpl")
        self.verticalLayout_4.addWidget(self.mpl)
        self.verticalLayout_2.addWidget(self.frame)
        self.frame_3 = QtGui.QFrame(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.frame_3)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtGui.QLabel(self.frame_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.serialPortLineEdit = QtGui.QLineEdit(self.frame_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.serialPortLineEdit.sizePolicy().hasHeightForWidth())
        self.serialPortLineEdit.setSizePolicy(sizePolicy)
        self.serialPortLineEdit.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.serialPortLineEdit.setObjectName("serialPortLineEdit")
        self.horizontalLayout_3.addWidget(self.serialPortLineEdit)
        self.connectCheckBox = QtGui.QCheckBox(self.frame_3)
        self.connectCheckBox.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.connectCheckBox.setObjectName("connectCheckBox")
        self.horizontalLayout_3.addWidget(self.connectCheckBox)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.verticalLayout_2.addWidget(self.frame_3)
        self.frame_2 = QtGui.QFrame(self.centralwidget)
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.frame_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.durationLabel = QtGui.QLabel(self.frame_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.durationLabel.sizePolicy().hasHeightForWidth())
        self.durationLabel.setSizePolicy(sizePolicy)
        self.durationLabel.setObjectName("durationLabel")
        self.horizontalLayout_2.addWidget(self.durationLabel)
        self.durationLineEdit = QtGui.QLineEdit(self.frame_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.durationLineEdit.sizePolicy().hasHeightForWidth())
        self.durationLineEdit.setSizePolicy(sizePolicy)
        self.durationLineEdit.setMaximumSize(QtCore.QSize(80, 16777215))
        self.durationLineEdit.setObjectName("durationLineEdit")
        self.horizontalLayout_2.addWidget(self.durationLineEdit)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.sampleRateLabel = QtGui.QLabel(self.frame_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sampleRateLabel.sizePolicy().hasHeightForWidth())
        self.sampleRateLabel.setSizePolicy(sizePolicy)
        self.sampleRateLabel.setObjectName("sampleRateLabel")
        self.horizontalLayout_2.addWidget(self.sampleRateLabel)
        self.sampleRateLineEdit = QtGui.QLineEdit(self.frame_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sampleRateLineEdit.sizePolicy().hasHeightForWidth())
        self.sampleRateLineEdit.setSizePolicy(sizePolicy)
        self.sampleRateLineEdit.setMaximumSize(QtCore.QSize(80, 16777215))
        self.sampleRateLineEdit.setObjectName("sampleRateLineEdit")
        self.horizontalLayout_2.addWidget(self.sampleRateLineEdit)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.rangeLabel = QtGui.QLabel(self.frame_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rangeLabel.sizePolicy().hasHeightForWidth())
        self.rangeLabel.setSizePolicy(sizePolicy)
        self.rangeLabel.setObjectName("rangeLabel")
        self.horizontalLayout_2.addWidget(self.rangeLabel)
        self.rangeComboBox = QtGui.QComboBox(self.frame_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rangeComboBox.sizePolicy().hasHeightForWidth())
        self.rangeComboBox.setSizePolicy(sizePolicy)
        self.rangeComboBox.setMaximumSize(QtCore.QSize(80, 16777215))
        self.rangeComboBox.setObjectName("rangeComboBox")
        self.horizontalLayout_2.addWidget(self.rangeComboBox)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.verticalLayout_2.addWidget(self.frame_2)
        self.frame_5 = QtGui.QFrame(self.centralwidget)
        self.frame_5.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout = QtGui.QHBoxLayout(self.frame_5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.startStopPushButton = QtGui.QPushButton(self.frame_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.startStopPushButton.sizePolicy().hasHeightForWidth())
        self.startStopPushButton.setSizePolicy(sizePolicy)
        self.startStopPushButton.setObjectName("startStopPushButton")
        self.horizontalLayout.addWidget(self.startStopPushButton)
        self.savePushButton = QtGui.QPushButton(self.frame_5)
        self.savePushButton.setObjectName("savePushButton")
        self.horizontalLayout.addWidget(self.savePushButton)
        spacerItem4 = QtGui.QSpacerItem(525, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.verticalLayout_2.addWidget(self.frame_5)
        self.frame_4 = QtGui.QFrame(self.centralwidget)
        self.frame_4.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout = QtGui.QVBoxLayout(self.frame_4)
        self.verticalLayout.setObjectName("verticalLayout")
        self.statusLabel = QtGui.QLabel(self.frame_4)
        self.statusLabel.setObjectName("statusLabel")
        self.verticalLayout.addWidget(self.statusLabel)
        self.verticalLayout_2.addWidget(self.frame_4)
        AccelSensorMainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(AccelSensorMainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 748, 23))
        self.menubar.setObjectName("menubar")
        AccelSensorMainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(AccelSensorMainWindow)
        self.statusbar.setObjectName("statusbar")
        AccelSensorMainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(AccelSensorMainWindow)
        QtCore.QMetaObject.connectSlotsByName(AccelSensorMainWindow)

    def retranslateUi(self, AccelSensorMainWindow):
        AccelSensorMainWindow.setWindowTitle(QtGui.QApplication.translate("AccelSensorMainWindow", "Accelerometer ADXL345", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("AccelSensorMainWindow", "Serial Port", None, QtGui.QApplication.UnicodeUTF8))
        self.serialPortLineEdit.setToolTip(QtGui.QApplication.translate("AccelSensorMainWindow", "set serial port address", None, QtGui.QApplication.UnicodeUTF8))
        self.connectCheckBox.setText(QtGui.QApplication.translate("AccelSensorMainWindow", "Connect", None, QtGui.QApplication.UnicodeUTF8))
        self.durationLabel.setText(QtGui.QApplication.translate("AccelSensorMainWindow", "Duration (s)", None, QtGui.QApplication.UnicodeUTF8))
        self.sampleRateLabel.setText(QtGui.QApplication.translate("AccelSensorMainWindow", "Sample Rate:", None, QtGui.QApplication.UnicodeUTF8))
        self.rangeLabel.setText(QtGui.QApplication.translate("AccelSensorMainWindow", "Range (g)", None, QtGui.QApplication.UnicodeUTF8))
        self.startStopPushButton.setToolTip(QtGui.QApplication.translate("AccelSensorMainWindow", "set current data log file", None, QtGui.QApplication.UnicodeUTF8))
        self.startStopPushButton.setText(QtGui.QApplication.translate("AccelSensorMainWindow", "Start", None, QtGui.QApplication.UnicodeUTF8))
        self.savePushButton.setText(QtGui.QApplication.translate("AccelSensorMainWindow", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.statusLabel.setText(QtGui.QApplication.translate("AccelSensorMainWindow", "Status:", None, QtGui.QApplication.UnicodeUTF8))

from mplwidget import MplWidget
